build-publish-azure: Add gallery to source images from (#415)
I had it exported in my env when I was testing the make target.

Fixes: 
```
# Update to my test offer for now
  make azure-marketplace-update-technical-plan-eap-dev \
  AZMARKETPLACE_PLAN=jvreeland_test_plan \
  AZMARKETPLACE_OFFER=jvreeland_test_offer \
  AZNAME="chainguard-eap-dev"
  shell: /usr/bin/bash -e {0}
  env:
    VM_CLOUD: azure
az extension remove -n partnercenter || true
ERROR: The extension partnercenter is not installed. Please install the extension via `az extension add -n partnercenter`.
az extension add --yes --source whl/partnercenter-0.2.7-py[3](https://github.com/chainguard-dev/wolfi-vm/actions/runs/15566617054/job/43835021890#step:8:3)-none-any.whl
WARNING: The installed extension 'partnercenter' is in preview.
Makefile:322: *** This gallery is not allowed listed in the makefile if you want to upload images from it please update the makefile..  Stop.
```

Because I want people to have to specify the gallery the images come
from so that VM testing images don't end up in the offer automation.
Hopefully that's improved when we split the subscription and the
resource groups.

Co-authored-by: Justin Vreeland <justin.vreeland@chainguard.com>