py3.12-torch-2.4-cuda-11.8: Use gcc-11 instead of gcc-12
This package ftbfs with:

  /usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../x86_64-pc-linux-gnu/bin/ld: lib/libc10.so: undefined reference to `std::condition_variable::wait(std::unique_lock<std::mutex>&)@GLIBCXX_3.4.30'"

This package used to build fine w/ gcc-12, but something has changed.
It works fine with gcc-11, and since this package should be removed soon,
there's no point in spending too much energy trying to make it work with
gcc-12.

https://github.com/chainguard-dev/internal-dev/issues/10603

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>