tritonserver-backend-tensorrtllm-cuda-12.9: Add -Wno-maybe-uninitialized to CXXFLAGS
Fixes FTBFS:

ninja: job failed: /usr/local/bin/g++-14 -DENABLE_BF16 -DENABLE_FP4 -DENABLE_FP8 -DTRITON_ENABLE_GPU=1 -DT
RACKER=1 -DTRITON_ENABLE_STATS=1 -DTRT_LLM_USE_DIM64 -I/home/build/backend/tensorrt_llm/triton_backend/inflight_batcher_llm/../.. -I/home/build/backend/tensorrt_llm/triton_backend/inflight_batcher_llm/../../cpp/include -I/home/build/backend/tensorrt_llm/triton_backend/inflight_batcher_llm -I/include -I/home/build/backend/tensorrt_llm/triton_backend/build/_deps/repo-common-src/include -I/home/build/backend/tensorrt_llm/triton_backend/build/_deps/repo-common-src/src/../include -I/home/build/backend/tensorrt_llm/triton_backend/build/_deps/repo-core-src/include -I/home/build/backend/tensorrt_llm/triton_backend/build/_deps/repo-backend-src/include -isystem /usr/local/cuda-12.9/include -O3 -DNDEBUG -fPIC -DENABLE_MULTI_DEVICE=1 -D_GLIBCXX_USE_CXX11_ABI=1 -Wall -Wextra -Wno-unused-parameter -Wno-deprecated-declarations -Werror -MD -MT CMakeFiles/triton-custom-metrics-reporter-library.dir/src/custom_metrics_reporter/custom_metrics_reporter.cc.o -MF CMakeFiles/triton-custom-metrics-reporter-library.dir/src/custom_metrics_reporter/custom_metrics_reporter.cc.o.d -o CMakeFiles/triton-custom-metrics-reporter-library.dir/src/custom_metrics_reporter/custom_metrics_reporter.cc.o -c /home/build/backend/tensorrt_llm/triton_backend/inflight_batcher_llm/src/custom_metrics_reporter/custom_metrics_reporter.cc
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/c++/x86_64-pc-linux-gnu/bits/c++allocator.h:33,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/c++/bits/allocator.h:46,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/c++/bits/alloc_traits.h:39,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/c++/ext/alloc_traits.h:34,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/c++/bits/hashtable_policy.h:39,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/c++/bits/hashtable.h:35,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/c++/bits/unordered_map.h:33,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/c++/unordered_map:41,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/c++/functional:63,
                 from /home/build/backend/tensorrt_llm/triton_backend/inflight_batcher_llm/src/custom_metrics_reporter/custom_metrics_reporter.h:30,
                 from /home/build/backend/tensorrt_llm/triton_backend/inflight_batcher_llm/src/custom_metrics_reporter/custom_metrics_reporter.cc:26:
In member function 'void std::__new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = double; _Args = {const double&}; _Tp = double]',
    inlined from 'static void std::allocator_traits<std::allocator<_Tp1> >::construct(allocator_type&, _Up*, _Args&& ...) [with _Up = double; _Args = {const double&}; _Tp = double]' at /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/c++/bits/alloc_traits.h:575:17,
    inlined from 'void std::vector<_Tp, _Alloc>::_M_realloc_append(_Args&& ...) [with _Args = {const double&}; _Tp = double; _Alloc = std::allocator<double>]' at /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/c++/bits/vector.tcc:634:26,
    inlined from 'void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = double; _Alloc = std::allocator<double>]' at /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/c++/bits/stl_vector.h:1307:21,
    inlined from 'TRITONSERVER_Error* triton::backend::inflight_batcher_llm::custom_metrics_reporter::CustomMetricsReporter::UpdateCustomMetrics(const std::string&)' at /home/build/backend/tensorrt_llm/triton_backend/inflight_batcher_llm/src/custom_metrics_reporter/custom_metrics_reporter.cc:271:42:
/usr/lib/gcc/x86_64-pc-linux-gnu/14/include/c++/bits/new_allocator.h:191:11: error: 'value' may be used uninitialized [-Werror=maybe-uninitialized]
  191 |         { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/build/backend/tensorrt_llm/triton_backend/inflight_batcher_llm/src/custom_metrics_reporter/custom_metrics_reporter.cc: In member function 'TRITONSERVER_Error* triton::backend::inflight_batcher_llm::custom_metrics_reporter::CustomMetricsReporter::UpdateCustomMetrics(const std::string&)':
/home/build/backend/tensorrt_llm/triton_backend/inflight_batcher_llm/src/custom_metrics_reporter/custom_metrics_reporter.cc:254:20: note: 'value' was declared here
  254 |             double value;
      |                    ^~~~~
cc1plus: all warnings being treated as errors
ninja: subcommand failed

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>