py3.10-vllm-cuda-11.8: Add missing nvrtc dep
Without this, local image testing fails with the following error:

Traceback (most recent call last):
  File "/app/offline_inference.py", line 14, in <module>
    llm = LLM(model="facebook/opt-125m")
  File "/usr/share/vllm/.venv/lib/python3.10/site-packages/vllm/utils.py", line 1051, in inner
    return fn(*args, **kwargs)
  File "/usr/share/vllm/.venv/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 242, in __init__
    self.llm_engine = self.engine_class.from_engine_args(
  File "/usr/share/vllm/.venv/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 484, in from_engine_args
    engine = cls(
  File "/usr/share/vllm/.venv/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 273, in __init__
    self.model_executor = executor_class(vllm_config=vllm_config, )
  File "/usr/share/vllm/.venv/lib/python3.10/site-packages/vllm/executor/executor_base.py", line 51, in __init__
    self._init_executor()
  File "/usr/share/vllm/.venv/lib/python3.10/site-packages/vllm/executor/uniproc_executor.py", line 40, in _init_executor
    self.collective_rpc("init_worker", args=([kwargs], ))
  File "/usr/share/vllm/.venv/lib/python3.10/site-packages/vllm/executor/uniproc_executor.py", line 51, in collective_rpc
    answer = run_method(self.driver_worker, method, args, kwargs)
  File "/usr/share/vllm/.venv/lib/python3.10/site-packages/vllm/utils.py", line 2220, in run_method
    return func(*args, **kwargs)
  File "/usr/share/vllm/.venv/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 551, in init_worker
    worker_class = resolve_obj_by_qualname(
  File "/usr/share/vllm/.venv/lib/python3.10/site-packages/vllm/utils.py", line 1906, in resolve_obj_by_qualname
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/share/vllm/.venv/lib/python3.10/site-packages/vllm/worker/worker.py", line 12, in <module>
    from vllm.device_allocator.cumem import CuMemAllocator
  File "/usr/share/vllm/.venv/lib/python3.10/site-packages/vllm/device_allocator/cumem.py", line 47, in <module>
    from vllm.cumem_allocator import (init_module, python_create_and_map,
ImportError: libnvrtc.so.11.2: cannot open shared object file: No such file or directory

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>