tritonserver-backend-tensorrtllm-cuda-12.9: Add dependency on py3-aiohttp
Discovered during testing:

bash-5.3# /usr/bin/trtllm-serve "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
/usr/lib/python3.12/site-packages/google/__init__.py:2: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  __import__('pkg_resources').declare_namespace(__name__)
/usr/lib/python3.12/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.29.5 is exactly one major version older than the runtime version 6.31.1 at onnx/onnx-ml.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
/usr/lib/python3.12/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.29.5 is exactly one major version older than the runtime version 6.31.1 at onnx/onnx-operators-ml.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
/usr/lib/python3.12/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.29.5 is exactly one major version older than the runtime version 6.31.1 at onnx/onnx-data.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
<frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.cuda module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.driver module instead.
<frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
Traceback (most recent call last):
  File "/usr/bin/trtllm-serve", line 5, in <module>
    from tensorrt_llm.commands.serve import main
  File "/usr/lib/python3.12/site-packages/tensorrt_llm/__init__.py", line 48, in <module>
    from .llmapi.llm import LLM, LlmArgs
  File "/usr/lib/python3.12/site-packages/tensorrt_llm/llmapi/__init__.py", line 5, in <module>
    from .llm import LLM, RequestOutput
  File "/usr/lib/python3.12/site-packages/tensorrt_llm/llmapi/llm.py", line 13, in <module>
    from tensorrt_llm.inputs.data import TextPrompt
  File "/usr/lib/python3.12/site-packages/tensorrt_llm/inputs/__init__.py", line 4, in <module>
    from .utils import (INPUT_FORMATTER_MAP, async_load_image, async_load_video,
  File "/usr/lib/python3.12/site-packages/tensorrt_llm/inputs/utils.py", line 8, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>