verticadb-operator-fips: set go version to v1.24 on go bump to fix build failure
The build fails with go v1.25
```
Error: failed to run update. Error: failed to run 'go mod tidy': exit status 2 with output: invalid value "1.25.5" for flag -go: maximum supported Go version is 1.24.11
```

This is partly due to a change in how go bump handles go-version[1]

Update to use go v1.24

[1] https://github.com/chainguard-dev/enterprise-packages/pull/44942

Signed-off-by: Brian Carey <brian.carey@chainguard.dev>