tritonserver: tensorrtllm backend (#9012)
* tritonserver: tensorrtllm backend

Version stream based on nvidia container release versions

See https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html

Signed-off-by: Pris Nasrat <pris.nasrat@chainguard.dev>

* Set the cuda version to 12.4

Signed-off-by: Pris Nasrat <pris.nasrat@chainguard.dev>

* Add hwloc and openmpi for cuda 12.4

Signed-off-by: Pris Nasrat <pris.nasrat@chainguard.dev>
[ dannf: Further bump openmpi to 5.0.6 and change
  dep on hwloc-cuda-12.5 to hwloc-cuda-12.4 ]
Signed-off-by: dann frazier <dann.frazier@chainguard.dev>

* tritonserver-backend-tensorrtllm-24.04: Correct commit hash for v0.9.0

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>

* tritonserver-backend-tensorrtllm-24.04: Add build-dep on grep

Avoids non-fatal error messages during build due to using busybox
grep, such as:

2024/11/20 17:47:11 INFO -- CMAKE_SYSTEM_PROCESSOR: x86_64
2024/11/20 17:47:11 WARN grep: invalid option -- 'P'
2024/11/20 17:47:11 WARN BusyBox v1.37.0 (2024-09-30 10:39:57 UTC) multi-call binary.
2024/11/20 17:47:11 WARN
2024/11/20 17:47:11 WARN Usage: grep [-HhnlLoqvsrRiwFE] [-m N] [-A|B|C N] { PATTERN | -e PATTERN... | -f FILE... } [FILE]...
2024/11/20 17:47:11 WARN
2024/11/20 17:47:11 WARN Search for PATTERN in FILEs (or stdin)
2024/11/20 17:47:11 WARN
2024/11/20 17:47:11 WARN     -H    Add 'filename:' prefix
2024/11/20 17:47:11 WARN     -h    Do not add 'filename:' prefix
2024/11/20 17:47:11 WARN     -n    Add 'line_no:' prefix
2024/11/20 17:47:11 WARN     -l    Show only names of files that match
2024/11/20 17:47:11 WARN     -L    Show only names of files that don't match
2024/11/20 17:47:11 WARN     -c    Show only count of matching lines
2024/11/20 17:47:11 WARN     -o    Show only the matching part of line
2024/11/20 17:47:11 WARN     -q    Quiet. Return 0 if PATTERN is found, 1 otherwise
2024/11/20 17:47:11 WARN     -v    Select non-matching lines
2024/11/20 17:47:11 WARN     -s    Suppress open and read errors
2024/11/20 17:47:11 WARN     -r    Recurse
2024/11/20 17:47:11 WARN     -R    Recurse and dereference symlinks
2024/11/20 17:47:11 WARN     -i    Ignore case
2024/11/20 17:47:11 WARN     -w    Match whole words only
2024/11/20 17:47:11 WARN     -x    Match whole lines only
2024/11/20 17:47:11 WARN     -F    PATTERN is a literal (not regexp)
2024/11/20 17:47:11 WARN     -E    PATTERN is an extended regexp
2024/11/20 17:47:11 WARN     -m N    Match up to N times per file
2024/11/20 17:47:11 WARN     -A N    Print N lines of trailing context
2024/11/20 17:47:11 WARN     -B N    Print N lines of leading context
2024/11/20 17:47:11 WARN     -C N    Same as '-A N -B N'
2024/11/20 17:47:11 WARN     -e PTRN    Pattern to match
2024/11/20 17:47:11 WARN     -f FILE    Read pattern from file
2024/11/20 17:47:11 WARN grep: invalid option -- 'P'

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>

* tritonserver-backend-tensorrtllm-24.04: Use > 20 cores if available

My build system has 32 cores, might as well use them.

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>

* tritonserver-backend-tensorrtllm-24.04: Remove unused tritonserver-version var

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>

* Add tensorrt-9.3 package

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>

* tritonserver-backend-tensorrtllm-24.04: Use compatible tensorrt/cudnn versions

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>

* openmpi-cuda-12.4: Merge packaging improvements from openmpi-cuda-12.5

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>

* tritonserver-backend-tensorrtllm-24.04: Cherry-pick build fix from r24.04 branch

The r24.04 branch has one change after the v0.9.0 tag. Without this
change, the build fails during the linking phase:

  2024/11/23 01:48:16 INFO [ 97%] Linking CXX executable triton_tensorrtllm_worker
  2024/11/23 01:48:16 WARN /usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/triton-tensorrt-llm-worker.dir/src/worker.cc.o: in function `tensorrt_llm::common::throwRuntimeError(char const*, int, std::string const&)':
  2024/11/23 01:48:16 WARN worker.cc:(.text.unlikely._ZN12tensorrt_llm6common17throwRuntimeErrorEPKciRKSs[_ZN12tensorrt_llm6common17throwRuntimeErrorEPKciRKSs]+0x4e): undefined reference to `tensorrt_llm::common::fmtstr(char const*, ...)'
  2024/11/23 01:48:16 WARN /usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../x86_64-pc-linux-gnu/bin/ld: worker.cc:(.text.unlikely._ZN12tensorrt_llm6common17throwRuntimeErrorEPKciRKSs[_ZN12tensorrt_llm6common17throwRuntimeErrorEPKciRKSs]+0x66): undefined reference to `tensorrt_llm::common::TllmException::TllmException(char const*, unsigned long, std::string const&)'
  2024/11/23 01:48:16 WARN /usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/triton-tensorrt-llm-worker.dir/src/worker.cc.o: in function `void tensorrt_llm::common::check<cudaError>(cudaError, char const*, char const*, int)':
  2024/11/23 01:48:16 WARN worker.cc:(.text._ZN12tensorrt_llm6common5checkI9cudaErrorEEvT_PKcS5_i[_ZN12tensorrt_llm6common5checkI9cudaErrorEEvT_PKcS5_i]+0x81): undefined reference to `tensorrt_llm::common::fmtstr(char const*, ...)'
  2024/11/23 01:48:16 WARN /usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../x86_64-pc-linux-gnu/bin/ld: worker.cc:(.text._ZN12tensorrt_llm6common5checkI9cudaErrorEEvT_PKcS5_i[_ZN12tensorrt_llm6common5checkI9cudaErrorEEvT_PKcS5_i]+0x92): undefined reference to `tensorrt_llm::common::TllmException::TllmException(char const*, unsigned long, std::string const&)'
  2024/11/23 01:48:16 WARN /usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/triton-tensorrt-llm-worker.dir/src/worker.cc.o: in function `main':
  2024/11/23 01:48:16 WARN worker.cc:(.text.startup+0x2bb): undefined reference to `tensorrt_llm::common::fmtstr(char const*, ...)'
  2024/11/23 01:48:16 WARN /usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../x86_64-pc-linux-gnu/bin/ld: worker.cc:(.text.startup+0x32d): undefined reference to `tensorrt_llm::common::fmtstr(char const*, ...)'
  2024/11/23 01:48:16 WARN /usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../x86_64-pc-linux-gnu/bin/ld: worker.cc:(.text.startup+0x449): undefined reference to `tensorrt_llm::common::fmtstr(char const*, ...)'
  2024/11/23 01:48:16 WARN /usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../x86_64-pc-linux-gnu/bin/ld: worker.cc:(.text.startup+0x483): undefined reference to `tensorrt_llm::common::fmtstr(char const*, ...)'
  2024/11/23 01:48:16 WARN /usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../x86_64-pc-linux-gnu/bin/ld: worker.cc:(.text.startup+0x54b): undefined reference to `tensorrt_llm::common::fmtstr(char const*, ...)'
  2024/11/23 01:48:16 WARN /usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/triton-tensorrt-llm-worker.dir/src/worker.cc.o:worker.cc:(.text.startup+0x5b4): more undefined references to `tensorrt_llm::common::fmtstr(char const*, ...)' follow
  2024/11/23 01:48:16 WARN /usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../x86_64-pc-linux-gnu/bin/ld: libtriton_tensorrtllm_common.so: undefined reference to `tensorrt_llm::batch_manager::GptManager::GptManager(std::filesystem::path const&, tensorrt_llm::batch_manager::TrtGptModelType, int, tensorrt_llm::batch_manager::batch_scheduler::SchedulerPolicy, std::function<std::list<std::shared_ptr<tensorrt_llm::batch_manager::InferenceRequest>, std::allocator<std::shared_ptr<tensorrt_llm::batch_manager::InferenceRequest> > > (int)>, std::function<void (unsigned long, std::list<tensorrt_llm::batch_manager::NamedTensor, std::allocator<tensorrt_llm::batch_manager::NamedTensor> > const&, bool, std::string const&)>, std::function<std::unordered_set<unsigned long, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<unsigned long> > ()>, std::function<void (std::string const&)>, tensorrt_llm::batch_manager::TrtGptModelOptionalParams const&, std::optional<unsigned long>, std::optional<int>, bool)'
  2024/11/23 01:48:16 WARN /usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../x86_64-pc-linux-gnu/bin/ld: libtriton_tensorrtllm_common.so: undefined reference to `tensorrt_llm::batch_manager::NamedTensor::NamedTensor(nvinfer1::DataType, std::vector<long, std::allocator<long> > const&, std::string, void const*)'
  2024/11/23 01:48:16 WARN collect2: error: ld returned 1 exit status

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>

* tritonserver-backend-tensorrtllm-24.04: Correct file installation list for v0.9.0

Update the reference URL and installed files for this version.
v0.9.0 does not produce libtensorrt_llm_nvrtc_wrapper.so or trtllmExecutorWorker.

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>

* tritonserver-backend-tensorrtllm-24.04: Also install .so version symlinks

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>

---------

Signed-off-by: Pris Nasrat <pris.nasrat@chainguard.dev>
Signed-off-by: dann frazier <dann.frazier@chainguard.dev>
Co-authored-by: dann frazier <dann.frazier@chainguard.dev>