fix disfunctional checkov package (#41522)
* fix disfunctional checkov package

alternatives considered:
1)
I kept going and going https://github.com/chainguard-dev/customer-issues/issues/2841#issuecomment-3597035527
to find out how long it takes to make checkov happy and turns out that
path is very long.
```bash
uv pip install argcomplete configargparse urllib3 pyyaml typing_extensions \
jmespath termcolor requests aiohttp bc_jsonpath_ng networkx colorama tqdm  \
junit_xml tabulate lark packaging pydantic detect_secrets prettytable boto3 \
dpath cachetools rustworkx python-hcl2 cloudsplaining docker pycep --system && checkov
```

even after adding all the deps above, checkov was still not happy and was
complaining about the following

```bash
ModuleNotFoundError: No module named 'pycep.typing'
```

we won't be able to apkify all those python packages (not including nested
deps), just the direct python apks itself is huge.

2)
I checked out python index https://libraries.cgr.dev/python/simple/checkov/
and checkov exists but it's broken, out of the dependencies that's listed
above, many of them are not available in out index so it'll require
few days/weeks to get all of this sorted.

pulling from pypi looked like the easiest/fastest path.

we'll need to withdraw package from wolfi post this.

Signed-off-by: kranurag7 <81210977+kranurag7@users.noreply.github.com>

* chore: link internal-dev issue about checkov fixes

Signed-off-by: kranurag7 <81210977+kranurag7@users.noreply.github.com>

* chore: use test/tw/ver-check pipeline

Signed-off-by: kranurag7 <81210977+kranurag7@users.noreply.github.com>

---------

Signed-off-by: kranurag7 <81210977+kranurag7@users.noreply.github.com>