tritonserver-backend-tensorrtllm-cuda-12.9: pin transformers to 4.51
Apparently upstream has this pinned for a reason:

bash-5.3# LD_LIBRARY_PATH=/usr/local/cuda-12.9/compat:/usr/local/tensorrt/targets/x86_64-linux-gnu/lib trtllm-serve "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
/usr/lib/python3.12/site-packages/google/__init__.py:2: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  __import__('pkg_resources').declare_namespace(__name__)
/usr/lib/python3.12/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.29.5 is exactly one major version older than the runtime version 6.31.1 at onnx/onnx-ml.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
/usr/lib/python3.12/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.29.5 is exactly one major version older than the runtime version 6.31.1 at onnx/onnx-operators-ml.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
/usr/lib/python3.12/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.29.5 is exactly one major version older than the runtime version 6.31.1 at onnx/onnx-data.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
<frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.cuda module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.driver module instead.
<frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
/usr/lib/python3.12/site-packages/modelopt/torch/__init__.py:36: UserWarning: transformers version 4.54.0 is incompatible with nvidia-modelopt and may cause issues. Please install recommended version with `pip install nvidia-modelopt[hf]` if working with HF models.
  _warnings.warn(
/usr/lib/python3.12/site-packages/torch/utils/cpp_extension.py:2356: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
[TensorRT-LLM] TensorRT-LLM version: 0.20.0
[07/28/2025-16:35:22] [TRT-LLM] [W] Overriding LlmArgs.max_input_len (annotation=int required=False default=1024 description='The maximum input length.') with build_config.max_input_len (1024).
[07/28/2025-16:35:22] [TRT-LLM] [W] Overriding LlmArgs.max_seq_len (annotation=Union[int, NoneType] required=False default=None description='The maximum sequence length.') with build_config.max_seq_len (None).
[07/28/2025-16:35:22] [TRT-LLM] [W] Overriding LlmArgs.max_beam_width (annotation=int required=False default=1 description='The maximum beam width.') with build_config.max_beam_width (1).
[07/28/2025-16:35:22] [TRT-LLM] [I] Set nccl_plugin to None.
Loading Model: [1/3]	Downloading HF model
Downloaded model to /root/.cache/huggingface/hub/models--TinyLlama--TinyLlama-1.1B-Chat-v1.0/snapshots/fe8a4ea1ffedaf415f4da2f062534de366a451e6
Time: 0.273s
Loading Model: [2/3]	Loading HF model to memory
[07/28/2025-16:35:22] [TRT-LLM] [I] Specified dtype 'auto'; inferred dtype 'bfloat16'.
[07/28/2025-16:35:22] [TRT-LLM] [W] Implicitly setting LLaMAConfig.has_partial_lora_mask = False
[07/28/2025-16:35:22] [TRT-LLM] [W] Implicitly setting LLaMAConfig.tie_word_embeddings = False
[07/28/2025-16:35:22] [TRT-LLM] [W] Implicitly setting LLaMAConfig.speculative_model = None
[07/28/2025-16:35:22] [TRT-LLM] [W] Implicitly setting LLaMAConfig.speculative_config = None
160it [00:00, 2762.93it/s]
Time: 0.301s
Loading Model: [3/3]	Building TRT-LLM engine
[07/28/2025-16:35:22] [TRT-LLM] [I] Set paged_kv_cache to True.
[07/28/2025-16:35:22] [TRT-LLM] [W] Overriding paged_state to False
[07/28/2025-16:35:22] [TRT-LLM] [I] Set paged_state to False.
[07/28/2025-16:35:22] [TRT-LLM] [I] Set dtype to bfloat16.
[07/28/2025-16:35:22] [TRT-LLM] [I] Set paged_state to False.
[07/28/2025-16:35:22] [TRT-LLM] [I] max_seq_len is not specified, using deduced value 2048
[07/28/2025-16:35:22] [TRT-LLM] [W] remove_input_padding is enabled, while opt_num_tokens is not set, setting to max_batch_size*max_beam_width.

[07/28/2025-16:35:22] [TRT-LLM] [W] padding removal and fMHA are both enabled, max_input_len is not required and will be ignored
[07/28/2025-16:35:22] [TRT-LLM] [I] Set use_fp8_context_fmha to False.
[07/28/2025-16:35:22] [TRT-LLM] [W] FP8 Context FMHA is disabled because it must be used together with the fp8 quantization workflow.
[07/28/2025-16:35:23] [TRT] [I] [MemUsageChange] Init CUDA: CPU -18, GPU +0, now: CPU 1457, GPU 425 (MiB)
[07/28/2025-16:35:25] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +1505, GPU +8, now: CPU 3156, GPU 433 (MiB)
[07/28/2025-16:35:25] [TRT-LLM] [I] Set nccl_plugin to None.
[07/28/2025-16:35:26] [TRT-LLM] [I] Total time of constructing network from module object 3.5271875858306885 seconds
[07/28/2025-16:35:26] [TRT-LLM] [I] Total optimization profiles added: 1
[07/28/2025-16:35:26] [TRT-LLM] [I] Total time to initialize the weights in network Unnamed Network 0: 00:00:00
[07/28/2025-16:35:26] [TRT-LLM] [I] Build TensorRT engine Unnamed Network 0
[07/28/2025-16:35:26] [TRT] [W] Unused Input: position_ids
[07/28/2025-16:35:26] [TRT] [W] [RemoveDeadLayers] Input Tensor position_ids is unused or used only at compile-time, but is not being removed.
[07/28/2025-16:35:26] [TRT] [I] Global timing cache in use. Profiling results in this builder pass will be stored.
[07/28/2025-16:35:26] [TRT] [I] Compiler backend is used during engine build.
[07/28/2025-16:35:48] [TRT] [I] [GraphReduction] The approximate region cut reduction algorithm is called.
[07/28/2025-16:35:48] [TRT] [I] Detected 17 inputs and 1 output network tensors.
[07/28/2025-16:35:49] [TRT] [I] Total Host Persistent Memory: 39856 bytes
[07/28/2025-16:35:49] [TRT] [I] Total Device Persistent Memory: 0 bytes
[07/28/2025-16:35:49] [TRT] [I] Max Scratch Memory: 377487360 bytes
[07/28/2025-16:35:49] [TRT] [I] [BlockAssignment] Started assigning block shifts. This will take 125 steps to complete.
[07/28/2025-16:35:49] [TRT] [I] [BlockAssignment] Algorithm ShiftNTopDown took 6.54476ms to assign 21 blocks to 125 nodes requiring 503325184 bytes.
[07/28/2025-16:35:49] [TRT] [I] Total Activation Memory: 503323136 bytes
[07/28/2025-16:35:50] [TRT] [I] Total Weights Memory: 2200621824 bytes
[07/28/2025-16:35:50] [TRT] [I] Compiler backend is used during engine execution.
[07/28/2025-16:35:50] [TRT] [I] Engine generation completed in 23.5447 seconds.
[07/28/2025-16:35:50] [TRT] [I] [MemUsageStats] Peak memory usage of TRT CPU/GPU memory allocators: CPU 0 MiB, GPU 2099 MiB
[07/28/2025-16:35:52] [TRT-LLM] [I] Total time of building Unnamed Network 0: 00:00:25
[07/28/2025-16:35:52] [TRT] [I] Serialized 1155 bytes of code generator cache.
[07/28/2025-16:35:52] [TRT] [I] Serialized 1559944 bytes of compilation cache.
[07/28/2025-16:35:52] [TRT] [I] Serialized 9 timing cache entries
[07/28/2025-16:35:52] [TRT-LLM] [I] Timing cache serialized to model.cache
[07/28/2025-16:35:52] [TRT-LLM] [I] Build phase peak memory: 13143.29 MB, children: 0.00 MB
Time: 30.310s
Loading model done.
Total latency: 30.884s
[07/28/2025-16:35:53] [TRT-LLM] [I] Serializing engine to /tmp/tmpnjggu03q-llm-workspace/tmp.engine/rank0.engine...
[07/28/2025-16:35:54] [TRT-LLM] [I] Engine serialized. Total time: 00:00:01
Traceback (most recent call last):
  File "/usr/sbin/trtllm-serve", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1363, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1830, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 794, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tensorrt_llm/commands/serve.py", line 225, in serve
    launch_server(host, port, llm_args)
  File "/usr/lib/python3.12/site-packages/tensorrt_llm/commands/serve.py", line 92, in launch_server
    llm = LLM(**llm_args)
          ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tensorrt_llm/llmapi/llm.py", line 176, in __init__
    raise e
  File "/usr/lib/python3.12/site-packages/tensorrt_llm/llmapi/llm.py", line 171, in __init__
    self._build_model()
  File "/usr/lib/python3.12/site-packages/tensorrt_llm/llmapi/llm.py", line 529, in _build_model
    self.input_processor = create_input_processor(self._hf_model_dir,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tensorrt_llm/inputs/registry.py", line 98, in create_input_processor
    from tensorrt_llm._torch.models import get_model_architecture
  File "/usr/lib/python3.12/site-packages/tensorrt_llm/_torch/models/__init__.py", line 9, in <module>
    from .modeling_llava_next import LlavaNextModel
  File "/usr/lib/python3.12/site-packages/tensorrt_llm/_torch/models/modeling_llava_next.py", line 283, in <module>
    AutoModel.register(LlavaNextConfig, LlavaNextModel)
  File "/usr/lib/python3.12/site-packages/transformers/models/auto/auto_factory.py", line 625, in register
    cls._model_mapping.register(config_class, model_class, exist_ok=exist_ok)
  File "/usr/lib/python3.12/site-packages/transformers/models/auto/auto_factory.py", line 873, in register
    raise ValueError(f"'{key}' is already used by a Transformers model.")
ValueError: '<class 'transformers.models.llava_next.configuration_llava_next.LlavaNextConfig'>' is already used by a Transformers model.

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>