Fix/py3 ftbfs packages (#5752)
* py3-adal - add test, drop python3 dependency.

The python3 dependency is not necessary as melange SCA adds it.
The test at least minimall verifies installation.

The openssl legacy runtime dependency on the test is required to
avoid RuntimeError in 'python3 -c import ada' like:

 > RuntimeError: OpenSSL 3.0's legacy provider failed to load.
 > This is a fatal error by default, but cryptography supports
 > running without legacy algorithms by setting the environment
 > variable CRYPTOGRAPHY_OPENSSL_NO_LEGACY. If you did not expect
 > this error, you have likely made a mistake with your OpenSSL configuration.

With a stacktrace like:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/[site-packages]/adal/__init__.py", line 34, in <module>
    from .authentication_context import AuthenticationContext
  File "/[site-packages]/adal/authentication_context.py", line 34, in <module>
    from .token_request import TokenRequest
  File "/[site-packages]/adal/token_request.py", line 34, in <module>
    from . import self_signed_jwt
  File "/[site-packages]/adal/self_signed_jwt.py", line 35, in <module>
    import jwt
  File "/[site-packages]/jwt/__init__.py", line 1, in <module>
    from .api_jwk import PyJWK, PyJWKSet
  File "/[site-packages]/jwt/api_jwk.py", line 7, in <module>
    from .algorithms import get_default_algorithms, has_crypto, requires_cryptography
  File "/[site-packages]/jwt/algorithms.py", line 12, in <module>
    from .utils import (
  File "/[site-packages]/jwt/utils.py", line 7, in <module>
    from cryptography.hazmat.primitives.asymmetric.ec import EllipticCurve
  File "/[site-packages]/cryptography/hazmat/primitives/asymmetric/ec.py", line 11, in <module>
    from cryptography.hazmat._oid import ObjectIdentifier
  File "/[site-packages]/cryptography/hazmat/_oid.py", line 7, in <module>
    from cryptography.hazmat.bindings._rust import (

Signed-off-by: Scott Moser <scott.moser@chainguard.dev>

* py3-applicationinsights - drop python-3 dep, add import test

Signed-off-by: Scott Moser <scott.moser@chainguard.dev>

* Update several py3-azure packages, py3-msal and py3-msrest.

These were all reported as FTBFS, but more than likely they
were all failing to run their tests.

They've been updated to:
 - drop the explicit python3 dep in runtime (it gets added by melange SCA)
 - make use of 'python/import' pipeline to test imports
   and replace the existing tests (that did the same thing).
 - added runtime dependencies found when running the tests.

Signed-off-by: Scott Moser <scott.moser@chainguard.dev>

---------

Signed-off-by: Scott Moser <scott.moser@chainguard.dev>