nemo: build-dep on the pytorch -dev package
nemo now fails to build with:

   /home/build/causal-conv1d/csrc/causal_conv1d.cpp:7:10: fatal error: torch/extension.h: No such file or directory
       7 | #include <torch/extension.h>
         |          ^~~~~~~~~~~~~~~~~~~
   compilation terminated.

After the refactor in commit 222178c92384e3b6026f7cd82f8a37c4ec9e49ca,
this header is now in the -dev package.

Fixes: https://github.com/chainguard-dev/enterprise-packages/issues/22724

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>