py3.10-torch-2.4-cuda-11.8: Fix FTBFS issues
This package was failing to build for a few reasons.

1) This package requires GCC 11 to build, and therefore had a build-dep
   on gcc-11-default. This makes gcc and g++ symlinks to gcc-11 and
   g++-11, respectively. But we've now introduced openssf-compiler-options,
   so gcc and g++ are now wrappers that append `-specs openssf.spec`.
   Since gcc-11 had been removed from wolfi, openssf-compiler-options
   didn't gain support for it, so this caused failures when no
   openssf.spec for gcc-11 was found. Here we avoid that by setting
   CC=gcc-11/CXX=g++-11 instead of using the default gcc/g++.
   This "fix" is now moot because we've since restored gcc-11 and
   added openssf-compiler-options support for it. But it's also
   not incorrect, so I've left it.

2) With the no-longer-built version of gcc-11 that was in wolfi,
   11.4.0, this package would eventually fail to build with:
     /usr/lib/gcc/x86_64-pc-linux-gnu/11.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: lib/libc10.so: undefined reference to `__pthread_cond_timedwait64'
   We've now bumped gcc-11 to 11.5.0 which appears to have resolved
   this issue.

3) Now that openssf-compiler-options is enabled for gcc-11, we need
   to disable the -fno-delete-null-pointer-checks option, which causes
   the following build error:
     .../torch-2.4.1+cu118/aten/src/ATen/core/boxing/KernelFunction_impl.h:177:39: error: non-constant condition for static assertion
     .../torch-2.4.1+cu118/aten/src/ATen/core/boxing/KernelFunction_impl.h:177:39: error: '(at::native::xnnpack::internal::convolution2d::conv2d_transpose_clamp_run != 0)' is not a constant expression

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>