make: fix UNTRUSTED signature on extras repository in local-wolfi (#1141)
Currently wolfi-base is used which does not have chainguard-keys
preinstalled, nor does the extras repository keyring injected into
local-wolfi target. Meaning upon `make local-wolfi`

```
$ make local-wolfi
fetch https://packages.wolfi.dev/os/x86_64/APKINDEX.tar.gz
fetch https://packages.cgr.dev/extras/x86_64/APKINDEX.tar.gz
WARNING: updating and opening https://packages.cgr.dev/extras: UNTRUSTED signature
WARNING: opening /work/packages: No such file or directory
ERROR: unable to select packages:
  vault-1.17 (no such package):
    required by: world[vault-1.17]
```

It is not usable by default. Switch to chainguard-base like
enterprise-package, such that extras keyring is trusted by default.

Thus:

```
$ make local-wolfi
WARNING: opening /work/packages: No such file or directory
(1/1) Installing vault-1.17 (1.17.5-r1)
OK: 365 MiB in 16 packages
```

Just works.