cuda-toolkit-12.1: cuda-toolkit: Add profiler-api to -dev
This is part of the CUDA toolkit and tensorrt_llm expects it:

```
2025/12/10 21:22:11 WARN /home/build/backend/tensorrt_llm/cpp/tensorrt_llm/executor/executorImpl.cpp:43:10: fatal error: cuda_profiler_api.h: No such file or directory
2025/12/10 21:22:11 WARN    43 | #include <cuda_profiler_api.h>
2025/12/10 21:22:11 WARN       |          ^~~~~~~~~~~~~~~~~~~~~
2025/12/10 21:22:11 WARN compilation terminated.
```

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>