tools: extract-compliance-reports: exit gracefully on failed test (#1140)
tools: extract-compliance-reports: exit gracefully on failed test

When the compliance/reports test failed, the content field in the 
artifacts file may be undefined. Make the extract-compliance-reports
tool fail gracefully in this case and provide a hint pointing to the 
previous failure.

This turns an error like:

    Traceback (most recent call last):
      File "/home/runner/work/wolfi-vm/wolfi-vm/./tools/extract-compliance-reports", line 59, in <module>
        main()
      File "/home/runner/work/wolfi-vm/wolfi-vm/./tools/extract-compliance-reports", line 41, in main
        report = base64.b64decode(file_obj["Content"])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/base64.py", line 83, in b64decode
        s = _bytes_from_decode_data(s)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/base64.py", line 45, in _bytes_from_decode_data
        raise TypeError("argument should be a bytes-like object or ASCII "
    TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'

into the more helpful:

    Artifacts file 'chainguard-eks-1.31-fips-dev/t4g.medium/compliance-reports-artifacts.json' \
    does not have any content for profile 'xccdf_org.ssgproject.content_profile_stig_draft24'! \
    Most likely the compliance/reports test failed. Please check 'test-reports.stderr'.

Signed-off-by: Markus Boehme <markus.boehme@chainguard.dev>