ct-manylinux-2.28: ignore all underlinking
Switch from ignoring missing symbols in just shared libraries (and
asserting in object files), to ignoring all underlinking (in both
object files and shared libraries).

This may lead to build failures and underlinked binaries.

But this also fixes lots of build failures, as python extension
modules (plugins) intentionally underlink and reference python C-abi
symbols from libpython, without actually linking against it. Which is
considered normal - see
[PEP-0513](https://peps.python.org/pep-0513/#libpythonx-y-so-1)

This resolves many failures to build from in the chainguard-2.28, for example:

    2025/06/05 12:54:58 INFO /bin/sh ../libtool  --tag=CC   --mode=link x86_64-pc-linux-gnu-gcc -pedantic -Wall -Wextra -Wshadow -Wpointer-arith -Wcast-align -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wno-long-long -Wno-format-extra-args -Wno-array-bounds -g -O2   -module -avoid-version  -o libxml2mod.la -rpath /usr/lib/python3.13/site-packages libxml.lo types.lo libxml2-py.lo ../libxml2.la
    2025/06/05 12:54:58 INFO libtool: link: x86_64-pc-linux-gnu-gcc -shared  -fPIC -DPIC  .libs/libxml.o .libs/types.o .libs/libxml2-py.o   -Wl,-rpath -Wl,/home/build/.libs ../.libs/libxml2.so -L/lib -ldl -lz -llzma -lm  -g -O2   -Wl,-soname -Wl,libxml2mod.so -o .libs/libxml2mod.so
    2025/06/05 12:54:58 WARN /usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: .libs/libxml.o: in function `libxml_xmlDebugMemory':
    2025/06/05 12:54:58 WARN /home/build/python/libxml.c:118:(.text+0x63): undefined reference to `PyArg_ParseTuple'
    2025/06/05 12:54:58 WARN /usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: .libs/libxml.o: in function `Py_INCREF':
    2025/06/05 12:54:58 WARN /usr/include/python3.13/object.h:824:(.text+0x253): undefined reference to `_Py_NoneStruct'
    2025/06/05 12:54:58 WARN /usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: .libs/libxml.o: in function `xmlPythonFileClose':
    2025/06/05 12:54:58 WARN /home/build/python/libxml.c:412:(.text+0x2a1): undefined reference to `PyObject_HasAttrString'
    2025/06/05 12:54:58 WARN /usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: /home/build/python/libxml.c:413:(.text+0x2bd): undefined reference to `PyObject_CallMethod'
    2025/06/05 12:54:58 WARN /usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: .libs/libxml.o: in function `Py_DECREF':
    2025/06/05 12:54:58 WARN /usr/include/python3.13/object.h:949:(.text+0x2d9): undefined reference to `_Py_Dealloc'
    2025/06/05 12:54:58 WARN /usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: .libs/libxml.o: in function `xmlPythonFileClose':
    2025/06/05 12:54:58 WARN /home/build/python/libxml.c:414:(.text+0x2f3): undefined reference to `PyObject_HasAttrString'