cve remediation GHSA-gmj6-6f8f-6699 and GHSA-q2x7-8rv6-6q7h torchvision cuda (#1578)
* fix(py3.10-torchvision-cuda-11.8 and py3.10-torchvision-cuda-12.3 and py3.11-torchvision-cuda-12.3): Add build-dep on cudnn-8

We were relying on a transitive dependency at build-time, which was removed
in chainguard-dev/extra-packages@0a193df.

This resolves build failure:

```
ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory
```

Signed-off-by: philroche <phil.roche@chainguard.dev>

* fix(py3.10-torchvision-cuda-11.8 and py3.10-torchvision-cuda-12.3 and py3.11-torchvision-cuda-12.3): Bump epoch to force rebuild to remediate two jinja2 CVEs

GHSA-q2x7-8rv6-6q7h [1] and GHSA-gmj6-6f8f-6699 [2] are both present in the current versions of py3.8-torchvision-cuda-11.8 and py3.9-torchvision-cuda-12.3 due to the dependency on jinja2.

All that is required is a rebuild of py3.8-torchvision-cuda-11.8 and py3.9-torchvision-cuda-12.3) which will update the jinja2 dependency from the
vulnerable 3.1.4 to the non vulnerable 3.1.5

[1] https://github.com/advisories/GHSA-q2x7-8rv6-6q7h
[2] https://github.com/advisories/GHSA-gmj6-6f8f-6699

Signed-off-by: philroche <phil.roche@chainguard.dev>

* fix(py3.11-torchvision-cuda-11.8.yaml): Downgrade cudnn version from 9 to 8 for py 3.11 torchvision

py 3.11 torchvision will fail build with error

```
ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory
```

The other py 3.11 torch packages also use nvidia-cudnn-8-cuda-11

Signed-off-by: philroche <phil.roche@chainguard.dev>

---------

Signed-off-by: philroche <phil.roche@chainguard.dev>
Co-authored-by: dann frazier <dann.frazier@chainguard.dev>