tritonserver-backend-vllm-24.04: venv dependency fixes
If we allow pip to fulfill deps when installing requirements-cuda.txt,
it will end up installing a non-CUDA torch into the venv.
This will make the python -c `import vllm` test fail:

File "/opt/tritonserver/venv/lib/python3.10/site-packages/torch/_library/fake_impl.py", line 31, in register
     if torch._C._dispatch_has_kernel_for_dispatch_key(self.qualname, "Meta"):
RuntimeError: operator torchvision::nms does not exist

Note: A more direct reproducer is:
  python -c `import torch; import torchvision`

Let's avoid that with --no-deps, but now we need to make sure
we have the deps we need. To do that, I iterated with
`import vllm`, adding the dependencies it complained about
each time until it succeeded without any error messages.
I used deps from wolfi when available, but safetensors and
triton were not.

Note: this test will pass if triton is missing, but
passive-aggressively:

$ python -c 'import vllm'
INFO 01-10 00:24:22 importing.py:15] Triton not installed or not compatible; certain GPU-related functions will not be available.
$

We could use a test case that would fail hard in this state.

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>