generic-image-upload: strip "slim" off Raspberry Pi image names (#1116)
After renaming all image configurations to follow a consistent scheme,
now the Raspberry Pi images don't match the file name pattern expected
by the website serving them anymore:

ERROR: RPI filename must match pattern:
rpi-generic-{base|docker}-arm64-YYYYMMDD-HHMMSS.raw.gz

generic-image-upload was already mangling the image name, having to add
the "generic" part. Now, in addition, it needs to strip the "slim" part.

https://github.com/chainguard-dev/wolfi-vm/actions/runs/19399668938

Signed-off-by: Markus Boehme <markus.boehme@chainguard.dev>