pr shard/cuda toolkit2 (#4727)
* cuda-toolkit-13.0: cuda-toolkit: Add libcufile

libcufile is provided with the toolkit but currently has to be manually
specified anywhere the library is used. Add it to the cuda-toolkit
metapackages so that it is always present

Signed-off-by: RJ Sampson <rj.sampson@chainguard.dev>

* cuda-toolkit-13.1: cuda-toolkit: Add libcufile

libcufile is provided with the toolkit but currently has to be manually
specified anywhere the library is used. Add it to the cuda-toolkit
metapackages so that it is always present

Signed-off-by: RJ Sampson <rj.sampson@chainguard.dev>

* cuda-toolkit-13.0: cuda-toolkit: Add profiler-api to -dev

This is part of the CUDA toolkit and tensorrt_llm expects it:

```
2025/12/10 21:22:11 WARN /home/build/backend/tensorrt_llm/cpp/tensorrt_llm/executor/executorImpl.cpp:43:10: fatal error: cuda_profiler_api.h: No such file or directory
2025/12/10 21:22:11 WARN    43 | #include <cuda_profiler_api.h>
2025/12/10 21:22:11 WARN       |          ^~~~~~~~~~~~~~~~~~~~~
2025/12/10 21:22:11 WARN compilation terminated.
```

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>

* cuda-toolkit-13.1: cuda-toolkit: Add profiler-api to -dev

This is part of the CUDA toolkit and tensorrt_llm expects it:

```
2025/12/10 21:22:11 WARN /home/build/backend/tensorrt_llm/cpp/tensorrt_llm/executor/executorImpl.cpp:43:10: fatal error: cuda_profiler_api.h: No such file or directory
2025/12/10 21:22:11 WARN    43 | #include <cuda_profiler_api.h>
2025/12/10 21:22:11 WARN       |          ^~~~~~~~~~~~~~~~~~~~~
2025/12/10 21:22:11 WARN compilation terminated.
```

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>

* cuda-toolkit-13.0: cuda-toolkit-12.[3-5]: Set license to MIT

This is our metapackage, not CUDA itself.

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>

* cuda-toolkit-13.0/LICENSE: cuda-toolkit-12.[3-5]: Set license to MIT

This is our metapackage, not CUDA itself.

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>

* cuda-toolkit-13.1: cuda-toolkit-12.[3-5]: Set license to MIT

This is our metapackage, not CUDA itself.

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>

* cuda-toolkit-13.1/LICENSE: cuda-toolkit-12.[3-5]: Set license to MIT

This is our metapackage, not CUDA itself.

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>

---------

Signed-off-by: RJ Sampson <rj.sampson@chainguard.dev>
Signed-off-by: dann frazier <dann.frazier@chainguard.dev>
Co-authored-by: RJ Sampson <rj.sampson@chainguard.dev>