Apparently we can only do 12 hrs with this method: (#590)
ERROR: (gcloud.storage.sign-url) Max valid duration allowed is 12h when
system-managed key is used. For longer duration, consider using the
private-key-file or an account authorized with `gcloud auth
activate-service-account`.