fix(datadog-agent): do not bundle BPF probes in embedded FS (#31617)
The flag --bundle-ebpf for the agent.build and system-probe.build Invoke build tasks,
makes oom-kill.o to fail because it's expected to be embedded in the Go binary embed.FS
at the path 'build', which is not [0].

When the --bundle-ebpf invoke flag is specified, the go binaries are built with the
build flag ebpf_bindata [1], which makes pkg/ebpf/bytecode.GetReader [2] to look for the
CO-RE BPF probes in the embed.FS binary-embedded filesystem at the overridden path
'build' [3], instead of the one specified by argument on the host FS [4], in case the agent
is compiled without the go build flag ebpf_bindata.

The problem comes for probes that are not included in the embedded FS [0], which
are copied over build/ at build time by the system-probe.build invoke task [5], ready
to be embedded during the go build.

oom-kill.o BPF probe is not included, which makes the loading of it,
when the agent's system probe is configured with the oom kill probe enabled [6]
and the agent Go binary compiled with the ebpf_bindata build flag, to fail.

Failure logs then look like below:
(/home/build/cmd/system-probe/modules/oom_kill_probe.go:31 in func13) | Starting the OOM Kill probe
(/home/build/pkg/collector/corechecks/ebpf/probe/oomkill/oom_kill.go:51 in NewProbe) | error loading CO-RE oom-kill probe: error reading oom-kill.o: open build/oom-kill.o: file does not exist. falling back to runtime compiled probe
(/home/build/pkg/util/kernel/find_headers.go:159 in GetKernelHeaders) | Unable to find kernel headers: no valid matching kernel header directories found. To download kernel headers, set system_probe_config.enable_kernel_header_download to true
(/home/build/cmd/system-probe/api/module/loader.go:95 in Register) | error creating module oom_kill_probe: unable to start the OOM kill probe: unable to find kernel headers
(/home/build/cmd/system-probe/subcommands/run/command.go:364 in startSystemProbe) | error while starting api server, exiting: failed to create system probe: no module could be loaded
Error: error while starting api server, exiting: failed to create system probe: no module could be loaded

This seems to be a potential bug in upstream, but we don't have a reason why
we should need some BPF probes embedded in the Go binary besides in the package.

0. https://github.com/DataDog/datadog-agent/blob/eab078f2e713852de8e4f4c168ea009065841903/pkg/ebpf/bytecode/asset_reader_bindata.go#L21
1. https://github.com/DataDog/datadog-agent/blob/17329b350f3e31ef8bb7906e842e1989486ec097/tasks/system_probe.py#L830
2. https://github.com/DataDog/datadog-agent/blob/eab078f2e713852de8e4f4c168ea009065841903/pkg/ebpf/co_re.go#L71
3. https://github.com/DataDog/datadog-agent/blob/eab078f2e713852de8e4f4c168ea009065841903/pkg/ebpf/bytecode/asset_reader_bindata.go#L29
4. https://github.com/DataDog/datadog-agent/blob/eab078f2e713852de8e4f4c168ea009065841903/pkg/ebpf/bytecode/asset_reader_nobindata.go#L18
5. https://github.com/DataDog/datadog-agent/blob/eab078f2e713852de8e4f4c168ea009065841903/tasks/system_probe.py#L1554
6. https://github.com/DataDog/helm-charts/blob/5e1d863df9725270aeb52959606e08b713a3cd38/charts/datadog/templates/system-probe-configmap.yaml#L31

Signed-off-by: Massimiliano Giovagnoli <massimiliano.giovagnoli@chainguard.dev>
Signed-off-by: maxgio92 <massimiliano.giovagnoli@chainguard.dev>