py3-tabulate: rename cleanup directory to fix FTBFS
`pip install` bails out with:

```
error: Multiple top-level packages discovered in a flat-layout: ['cleanup', 'tabulate'].
```

due to the current naming.