py3.12-torchvision-cuda-12.3: Remove setuptools from venv
The build was failing with:
  error: invalid command 'bdist_wheel'

The py3.10 variant builds fine however, and this seems to
be the significant difference. Presumably it helps because
the venv had a setuptools==70.0.0 from the py3.12-pytorch
build, and this lets it use the latest version.

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>