ghidra/11.4 package update (#26159)
* ghidra/11.4 package update

Signed-off-by: wolfi-bot <121097084+wolfi-bot@users.noreply.github.com>

* rewrite the old patch, Upstream did not merged the pr mentioned but did update some of the deps

Signed-off-by: Debasish Biswas <debasishbsws.dev@gmail.com>

* fix(build): remove .orig files after patching to avoid IP resolution error

- After applying build.patch, backup files with .orig extension are generated
- These leftover .orig files, such as Module.manifest.orig, cause issues during build:
  Error: 'No IP found for .../Module.manifest.orig'
- This happens because the build system tries to interpret the .orig files as valid module definitions
- Added a cleanup step to delete all *.orig files after patching to prevent build failure

Signed-off-by: Debasish Biswas <debasishbsws.dev@gmail.com>

* Update the patch from a correct base

 In my last commit I had recreate the patch from the current master which was iuncorrect and I should have re create the patch from aed1cf1c4e060af395af241f0e6027be783b9591 commit

Signed-off-by: Debasish Biswas <debasishbsws.dev@gmail.com>

* Update build.patch again

Signed-off-by: Debasish Biswas <debasishbsws.dev@gmail.com>

* Try fixing GHSA-735f-pc8j-v9w8

Signed-off-by: Debasish Biswas <debasishbsws.dev@gmail.com>

* try fixing GHSA-hq9p-pm7w-8p54

Signed-off-by: Debasish Biswas <debasishbsws.dev@gmail.com>

* Fix license change for postgresql

Signed-off-by: Debasish Biswas <debasishbsws.dev@gmail.com>

---------

Signed-off-by: wolfi-bot <121097084+wolfi-bot@users.noreply.github.com>
Signed-off-by: Debasish Biswas <debasishbsws.dev@gmail.com>
Co-authored-by: wolfi-bot <121097084+wolfi-bot@users.noreply.github.com>
Co-authored-by: Debasish Biswas <debasishbsws.dev@gmail.com>