-std=gnu++20
      |                                                                                                                      ^
/tmp/tmpxft_00000009_00000000-6_low_latency_fp8_gemm_fp16.cudafe1.stub.c:63:3186:   required from here
   63 | om< ::cute::SM90_U32x4_STSM_N,  ::cutlass::half_t > , void > , void, void> ::Params _ZN7cutlass4gemm6kernel13GemmUniversalIN4cute5tupleIJiiiiEEENS0_10collective13CollectiveMmaINS0_46MainloopSm90TmaGmmaWarpSpecializedWithPrefetchILi6ENS4_IJNS3_1CILi8EEENS9_ILi1EEESB_EEENS0_59KernelTmaWarpSpecializedFP8FastAccumWithPrefetchAndSplitDMAEEENS4_IJNS9_ILi128EEESF_SF_EEENS_12float_e4m3_tENS4_IJlSB_lEEESH_SI_NS3_8TiledMMAINS3_8MMA_AtomIJNS3_4SM904GMMA31MMA_64x128x32_F32E4M3E4M3_SS_TNILNSM_7ScaleInE1ELSO_1EEEEEENS3_6LayoutINS4_IJSB_SB_SB_EEENS4_IJNS9_ILi0EEEST_ST_EEEEENS4_IJNS3_10UnderscoreESW_SW_EEEEENS3_13SM90_TMA_LOADENS3_14ComposedLayoutINS3_7SwizzleILi3ELi4ELi3EEENS3_18smem_ptr_flag_bitsILi8EEENSR_INS4_IJSA_SF_EEENS4_IJSF_SB_EEEEEEEvNS3_8identityENS3_23SM90_TMA_LOAD_MULTICASTES18_vS19_EENS_8epilogue10collective18CollectiveEpilogueINS1C_22Sm90TmaWarpSpecializedILi4ELi2ELi16ELb1ELb0EEEJSG_NS4_IJNS9_ILi64EEENS9_ILi32EEEEEENS_6half_tENS4_IJSB_llEEES1K_S1L_NS1C_6fusion15FusionCallbacksIS1G_NS1M_17LinearCombinationIS1K_fS1K_fLNS_15FloatRoundStyleE2EEESG_S1J_JEEESZ_NS10_IS12_NS13_ILi16EEENSR_INS4_IJS1H_SA_EEENS4_IJSB_S1H_EEEEEEENS3_17SM75_U16x8_LDSM_TENS3_14SM90_TMA_STOREES1W_NS3_17SM90_U16x8_STSM_TENS3_9Copy_AtomIJNS3_17SM90_U32x4_STSM_NES1K_EEEvEEEvvE6ParamsE;
      |                                                                            ^~

/home/build/backend/tensorrt_llm/3rdparty/cutlass/examples/63_hopper_gemm_with_weight_prefetch/collective/sm90_mma_tma_gmma_ss_warpspecialized_with_prefetch.hpp:160:63: error: non-type template parameters of class type only available with '-std=c++20' or '-std=gnu++20'
  160 |   using PrefetchSmemLayoutA = decltype(make_layout(make_shape(
      |                                                     ~~~~~~~~~~^
/home/build/backend/tensorrt_llm/3rdparty/cutlass/examples/63_hopper_gemm_with_weight_prefetch/collective/sm90_mma_tma_gmma_ss_warpspecialized_with_prefetch.hpp:160:63: error: non-type template parameters of class type only available with '-std=c++20' or '-std=gnu++20'

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>