Sync python-3.X.yaml changes from wolfi to python 3.8, 3.9
The changes here make python 3.8 and 3.9 similarly packaged
to python 3.10 and 3.11 and 3.12 in wolfi.

See https://github.com/wolfi-dev/os/pull/15076 for more information.

The big win is that now you can:

    apk add python-3.8-base python-3.9-base python-3.12-base
    apk add python-3.12

That is to say, that the 'base' varieties are co-installable.
The non-base version installs symlinks 'python3 -> python.XX'
in /usr/bin

Also includes https://github.com/wolfi-dev/os/pull/15120

Note that python-3.7 is not like the others, a simple copy of the
template does not build. it fails with:

running pipeline for subpackage python-3.7-base
'melange-out/python-3.7/usr/lib/python3.7' ->
   'melange-out/python-3.7-base/usr/lib/python3.7'
'melange-out/python-3.7/usr/lib/libpython3.7.so.*' ->
   'melange-out/python-3.7-base/usr/lib/libpython3.7.so.*'
mv: can't rename 'melange-out/python-3.7/usr/lib/libpython3.7.so.*':
   No such file or directory
ERROR: failed to build package. the build environment has been preserved: