frr-8.4/8.4.7 package update (#12326)
* frr-8.4/8.4.7 package update

Signed-off-by: wolfi-bot <121097084+wolfi-bot@users.noreply.github.com>

* fix(build): Pin Python Version to 3.12 to Fix Build Errors with Deprecated API Functions

- The build was failing during the compilation of lib/clippy.c due to the use of deprecated Python API functions. Specifically, the function Py_SetStandardStreamEncoding is no longer available in Python 3.13, resulting in the following error:

  lib/clippy.c:52:9: error: implicit declaration of function 'Py_SetStandardStreamEncoding' [-Wimplicit-function-declaration]

- This error falls under the category of Build/Python API Compatibility, caused by the removal of certain older Python API functions in Python 3.13.

- To address this issue, the Python version has been pinned to Python 3.12, which still supports the required API functions.

Signed-off-by: Debasish Biswas <debasishbsws.dev@gmail.com>

---------

Signed-off-by: wolfi-bot <121097084+wolfi-bot@users.noreply.github.com>
Signed-off-by: Debasish Biswas <debasishbsws.dev@gmail.com>
Co-authored-by: wolfi-bot <121097084+wolfi-bot@users.noreply.github.com>
Co-authored-by: Debasish Biswas <debasishbsws.dev@gmail.com>